apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bmi-app

  template:
    metadata:
      labels:
        app: bmi-app

    spec:
      containers:
      - name: bmi-container
        image: bmi-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
